version: '3.8'

services:
  app:
    image: yourusername/random-walk:v1.0.0  # Replace with your DockerHub username
    ports:
      - "4000:4000"
    volumes:
      - random-walk_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  random-walk_data: 